#!/usr/bin/env bash

#me=$(basename "$0")
#bin=$(cd "$(dirname "$0")" && /bin/pwd)

pid=$1
export TARGET_PID=$pid
export LD_PRELOAD=`/bin/pwd`/libplebconf.so


err()	{ echo >&2 "$*"; }
log()	{ err  "$me: $*"; }
vlog()	{ $verbose && log "$*"; }
fail()	{ log "$*"; exit 1; }
rawecho() { echo -E "x$*" | sed 's/^x//'; }
prefix()  { sed "s/^/$me: /"; }

/sbin/ifconfig $2 $3 $4 $5 $6